# Generated by Django 5.1.4 on 2024-12-26 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionimage',
            name='image_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
